// Code generated by protoc-gen-go. DO NOT EDIT.
// source: entityservice/entity.proto

package entityservice

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Record represents a db record
type Record struct {
	Id                   string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Fields               map[string]*FieldValue `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *Record) Reset()         { *m = Record{} }
func (m *Record) String() string { return proto.CompactTextString(m) }
func (*Record) ProtoMessage()    {}
func (*Record) Descriptor() ([]byte, []int) {
	return fileDescriptor_92eca7b48a44f851, []int{0}
}

func (m *Record) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Record.Unmarshal(m, b)
}
func (m *Record) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Record.Marshal(b, m, deterministic)
}
func (m *Record) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Record.Merge(m, src)
}
func (m *Record) XXX_Size() int {
	return xxx_messageInfo_Record.Size(m)
}
func (m *Record) XXX_DiscardUnknown() {
	xxx_messageInfo_Record.DiscardUnknown(m)
}

var xxx_messageInfo_Record proto.InternalMessageInfo

func (m *Record) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Record) GetFields() map[string]*FieldValue {
	if m != nil {
		return m.Fields
	}
	return nil
}

type Id struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Id) Reset()         { *m = Id{} }
func (m *Id) String() string { return proto.CompactTextString(m) }
func (*Id) ProtoMessage()    {}
func (*Id) Descriptor() ([]byte, []int) {
	return fileDescriptor_92eca7b48a44f851, []int{1}
}

func (m *Id) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Id.Unmarshal(m, b)
}
func (m *Id) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Id.Marshal(b, m, deterministic)
}
func (m *Id) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Id.Merge(m, src)
}
func (m *Id) XXX_Size() int {
	return xxx_messageInfo_Id.Size(m)
}
func (m *Id) XXX_DiscardUnknown() {
	xxx_messageInfo_Id.DiscardUnknown(m)
}

var xxx_messageInfo_Id proto.InternalMessageInfo

func (m *Id) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type FieldValue struct {
	FType                string   `protobuf:"bytes,1,opt,name=fType,proto3" json:"fType,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FieldValue) Reset()         { *m = FieldValue{} }
func (m *FieldValue) String() string { return proto.CompactTextString(m) }
func (*FieldValue) ProtoMessage()    {}
func (*FieldValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_92eca7b48a44f851, []int{2}
}

func (m *FieldValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FieldValue.Unmarshal(m, b)
}
func (m *FieldValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FieldValue.Marshal(b, m, deterministic)
}
func (m *FieldValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FieldValue.Merge(m, src)
}
func (m *FieldValue) XXX_Size() int {
	return xxx_messageInfo_FieldValue.Size(m)
}
func (m *FieldValue) XXX_DiscardUnknown() {
	xxx_messageInfo_FieldValue.DiscardUnknown(m)
}

var xxx_messageInfo_FieldValue proto.InternalMessageInfo

func (m *FieldValue) GetFType() string {
	if m != nil {
		return m.FType
	}
	return ""
}

func (m *FieldValue) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type QueryRequest struct {
	Stmt                 string   `protobuf:"bytes,1,opt,name=stmt,proto3" json:"stmt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryRequest) Reset()         { *m = QueryRequest{} }
func (m *QueryRequest) String() string { return proto.CompactTextString(m) }
func (*QueryRequest) ProtoMessage()    {}
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_92eca7b48a44f851, []int{3}
}

func (m *QueryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryRequest.Unmarshal(m, b)
}
func (m *QueryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryRequest.Marshal(b, m, deterministic)
}
func (m *QueryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRequest.Merge(m, src)
}
func (m *QueryRequest) XXX_Size() int {
	return xxx_messageInfo_QueryRequest.Size(m)
}
func (m *QueryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRequest proto.InternalMessageInfo

func (m *QueryRequest) GetStmt() string {
	if m != nil {
		return m.Stmt
	}
	return ""
}

type QueryResponse struct {
	Records              []*Record `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *QueryResponse) Reset()         { *m = QueryResponse{} }
func (m *QueryResponse) String() string { return proto.CompactTextString(m) }
func (*QueryResponse) ProtoMessage()    {}
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_92eca7b48a44f851, []int{4}
}

func (m *QueryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryResponse.Unmarshal(m, b)
}
func (m *QueryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryResponse.Marshal(b, m, deterministic)
}
func (m *QueryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryResponse.Merge(m, src)
}
func (m *QueryResponse) XXX_Size() int {
	return xxx_messageInfo_QueryResponse.Size(m)
}
func (m *QueryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryResponse proto.InternalMessageInfo

func (m *QueryResponse) GetRecords() []*Record {
	if m != nil {
		return m.Records
	}
	return nil
}

type RecordSaveStatus struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status               bool     `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RecordSaveStatus) Reset()         { *m = RecordSaveStatus{} }
func (m *RecordSaveStatus) String() string { return proto.CompactTextString(m) }
func (*RecordSaveStatus) ProtoMessage()    {}
func (*RecordSaveStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_92eca7b48a44f851, []int{5}
}

func (m *RecordSaveStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecordSaveStatus.Unmarshal(m, b)
}
func (m *RecordSaveStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecordSaveStatus.Marshal(b, m, deterministic)
}
func (m *RecordSaveStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecordSaveStatus.Merge(m, src)
}
func (m *RecordSaveStatus) XXX_Size() int {
	return xxx_messageInfo_RecordSaveStatus.Size(m)
}
func (m *RecordSaveStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_RecordSaveStatus.DiscardUnknown(m)
}

var xxx_messageInfo_RecordSaveStatus proto.InternalMessageInfo

func (m *RecordSaveStatus) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *RecordSaveStatus) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

type SaveResponse struct {
	SaveStatuses         []*RecordSaveStatus `protobuf:"bytes,1,rep,name=saveStatuses,proto3" json:"saveStatuses,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *SaveResponse) Reset()         { *m = SaveResponse{} }
func (m *SaveResponse) String() string { return proto.CompactTextString(m) }
func (*SaveResponse) ProtoMessage()    {}
func (*SaveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_92eca7b48a44f851, []int{6}
}

func (m *SaveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveResponse.Unmarshal(m, b)
}
func (m *SaveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveResponse.Marshal(b, m, deterministic)
}
func (m *SaveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveResponse.Merge(m, src)
}
func (m *SaveResponse) XXX_Size() int {
	return xxx_messageInfo_SaveResponse.Size(m)
}
func (m *SaveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SaveResponse proto.InternalMessageInfo

func (m *SaveResponse) GetSaveStatuses() []*RecordSaveStatus {
	if m != nil {
		return m.SaveStatuses
	}
	return nil
}

type RecordArr struct {
	Records              []*Record `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *RecordArr) Reset()         { *m = RecordArr{} }
func (m *RecordArr) String() string { return proto.CompactTextString(m) }
func (*RecordArr) ProtoMessage()    {}
func (*RecordArr) Descriptor() ([]byte, []int) {
	return fileDescriptor_92eca7b48a44f851, []int{7}
}

func (m *RecordArr) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecordArr.Unmarshal(m, b)
}
func (m *RecordArr) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecordArr.Marshal(b, m, deterministic)
}
func (m *RecordArr) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecordArr.Merge(m, src)
}
func (m *RecordArr) XXX_Size() int {
	return xxx_messageInfo_RecordArr.Size(m)
}
func (m *RecordArr) XXX_DiscardUnknown() {
	xxx_messageInfo_RecordArr.DiscardUnknown(m)
}

var xxx_messageInfo_RecordArr proto.InternalMessageInfo

func (m *RecordArr) GetRecords() []*Record {
	if m != nil {
		return m.Records
	}
	return nil
}

func init() {
	proto.RegisterType((*Record)(nil), "entityservice.Record")
	proto.RegisterMapType((map[string]*FieldValue)(nil), "entityservice.Record.FieldsEntry")
	proto.RegisterType((*Id)(nil), "entityservice.Id")
	proto.RegisterType((*FieldValue)(nil), "entityservice.FieldValue")
	proto.RegisterType((*QueryRequest)(nil), "entityservice.QueryRequest")
	proto.RegisterType((*QueryResponse)(nil), "entityservice.QueryResponse")
	proto.RegisterType((*RecordSaveStatus)(nil), "entityservice.RecordSaveStatus")
	proto.RegisterType((*SaveResponse)(nil), "entityservice.SaveResponse")
	proto.RegisterType((*RecordArr)(nil), "entityservice.RecordArr")
}

func init() { proto.RegisterFile("entityservice/entity.proto", fileDescriptor_92eca7b48a44f851) }

var fileDescriptor_92eca7b48a44f851 = []byte{
	// 434 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x93, 0xc1, 0x72, 0xd3, 0x30,
	0x10, 0x86, 0x6b, 0x97, 0x18, 0xb2, 0x49, 0x98, 0xa2, 0x29, 0x8c, 0x31, 0xcc, 0x10, 0x74, 0xca,
	0x05, 0x7b, 0x26, 0x30, 0x50, 0x3a, 0x1c, 0x08, 0x50, 0x98, 0x1c, 0x51, 0x0a, 0x07, 0x6e, 0x6a,
	0xbc, 0x75, 0x0d, 0xa9, 0x6d, 0x24, 0xd9, 0x8c, 0xdf, 0x83, 0x97, 0xe0, 0x2d, 0x19, 0x4b, 0x6a,
	0x13, 0xbb, 0xbe, 0xc0, 0x4d, 0xda, 0xfd, 0xfe, 0x7f, 0x57, 0x7f, 0x62, 0x08, 0x30, 0x53, 0xa9,
	0xaa, 0x25, 0x8a, 0x2a, 0x5d, 0x63, 0x64, 0x6e, 0x61, 0x21, 0x72, 0x95, 0x93, 0x49, 0xab, 0x47,
	0xff, 0x38, 0xe0, 0x31, 0x5c, 0xe7, 0x22, 0x26, 0x77, 0xc1, 0x4d, 0x63, 0xdf, 0x99, 0x3a, 0xb3,
	0x21, 0x73, 0xd3, 0x98, 0xbc, 0x06, 0xef, 0x3c, 0xc5, 0x4d, 0x2c, 0x7d, 0x77, 0xba, 0x3f, 0x1b,
	0xcd, 0x9f, 0x86, 0x2d, 0x69, 0x68, 0x64, 0xe1, 0x47, 0xcd, 0x9c, 0x64, 0x4a, 0xd4, 0xcc, 0x0a,
	0x82, 0x53, 0x18, 0xed, 0x94, 0xc9, 0x01, 0xec, 0xff, 0xc0, 0xda, 0x5a, 0x37, 0x47, 0x12, 0xc1,
	0xa0, 0xe2, 0x9b, 0x12, 0x7d, 0x77, 0xea, 0xcc, 0x46, 0xf3, 0x87, 0x1d, 0x6b, 0x2d, 0xfe, 0xda,
	0x00, 0xcc, 0x70, 0xc7, 0xee, 0x91, 0x43, 0x0f, 0xc1, 0x5d, 0xde, 0x58, 0x93, 0x1e, 0x01, 0x6c,
	0x71, 0x72, 0x08, 0x83, 0xf3, 0xd3, 0xba, 0x40, 0x0b, 0x98, 0x4b, 0x53, 0xdd, 0x8e, 0x1b, 0x5a,
	0x4f, 0x4a, 0x61, 0xfc, 0xb9, 0x44, 0x51, 0x33, 0xfc, 0x59, 0xa2, 0x54, 0x84, 0xc0, 0x2d, 0xa9,
	0x2e, 0x95, 0x95, 0xea, 0x33, 0x7d, 0x0b, 0x13, 0xcb, 0xc8, 0x22, 0xcf, 0x24, 0x92, 0x08, 0x6e,
	0x0b, 0xfd, 0x70, 0xe9, 0x3b, 0x3a, 0x96, 0xfb, 0xbd, 0xb1, 0xb0, 0x2b, 0x8a, 0x1e, 0xc3, 0x81,
	0x29, 0xad, 0x78, 0x85, 0x2b, 0xc5, 0x55, 0x29, 0x6f, 0x44, 0xfd, 0x00, 0x3c, 0xa9, 0x3b, 0x7a,
	0xc1, 0x3b, 0xcc, 0xde, 0xe8, 0x0a, 0xc6, 0x8d, 0xea, 0x7a, 0xf8, 0x7b, 0x18, 0xcb, 0x6b, 0x17,
	0xbc, 0xda, 0xe0, 0x49, 0xef, 0x06, 0xdb, 0x71, 0xac, 0x25, 0xa2, 0x6f, 0x60, 0x68, 0x88, 0x85,
	0x10, 0xff, 0xfc, 0x9c, 0xf9, 0x6f, 0x17, 0x26, 0x27, 0x9a, 0x58, 0x19, 0x82, 0xbc, 0x82, 0xe1,
	0x27, 0x54, 0xf6, 0x4f, 0x74, 0xaf, 0x23, 0x5f, 0xc6, 0x41, 0xbf, 0x23, 0xdd, 0x23, 0x1f, 0x60,
	0xa0, 0xb3, 0x25, 0x8f, 0x3a, 0xc4, 0xee, 0xaf, 0x12, 0x3c, 0xee, 0x6f, 0x9a, 0x44, 0xe8, 0x1e,
	0x59, 0x80, 0xb7, 0xcc, 0x24, 0x0a, 0x45, 0xfc, 0xde, 0x41, 0x0b, 0x21, 0x82, 0xee, 0x80, 0xdd,
	0x50, 0x8d, 0xc5, 0x97, 0x22, 0xe6, 0x0a, 0xff, 0xdb, 0xe2, 0xdd, 0xcb, 0x6f, 0x2f, 0x92, 0x54,
	0x5d, 0x94, 0x67, 0xe1, 0x3a, 0xbf, 0x8c, 0xaa, 0x34, 0xcb, 0xe3, 0x0b, 0xc1, 0xbf, 0xf3, 0x24,
	0x2f, 0xf8, 0x26, 0xfa, 0xc5, 0xeb, 0x2c, 0xe1, 0xcf, 0x12, 0x51, 0xac, 0xa3, 0x96, 0xcd, 0x99,
	0xa7, 0xbf, 0xca, 0xe7, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0xeb, 0xf2, 0x6d, 0xcc, 0xb3, 0x03,
	0x00, 0x00,
}
