// Code generated by protoc-gen-go. DO NOT EDIT.
// source: signup/signup.proto

package orgsignup

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	entityservice "github.com/vinodhrajagopal/waynga-grpc/entityservice"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type OrgSignupRequest struct {
	Name                 string             `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Phone                string             `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	Email                string             `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Admin                *UserSignupRequest `protobuf:"bytes,4,opt,name=admin,proto3" json:"admin,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *OrgSignupRequest) Reset()         { *m = OrgSignupRequest{} }
func (m *OrgSignupRequest) String() string { return proto.CompactTextString(m) }
func (*OrgSignupRequest) ProtoMessage()    {}
func (*OrgSignupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d51c8882b3c28c6, []int{0}
}

func (m *OrgSignupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrgSignupRequest.Unmarshal(m, b)
}
func (m *OrgSignupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrgSignupRequest.Marshal(b, m, deterministic)
}
func (m *OrgSignupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrgSignupRequest.Merge(m, src)
}
func (m *OrgSignupRequest) XXX_Size() int {
	return xxx_messageInfo_OrgSignupRequest.Size(m)
}
func (m *OrgSignupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OrgSignupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OrgSignupRequest proto.InternalMessageInfo

func (m *OrgSignupRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *OrgSignupRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *OrgSignupRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *OrgSignupRequest) GetAdmin() *UserSignupRequest {
	if m != nil {
		return m.Admin
	}
	return nil
}

type UserSignupRequest struct {
	FirstName            string   `protobuf:"bytes,1,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName             string   `protobuf:"bytes,2,opt,name=lastName,proto3" json:"lastName,omitempty"`
	UserName             string   `protobuf:"bytes,3,opt,name=userName,proto3" json:"userName,omitempty"`
	Phone                string   `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	Email                string   `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserSignupRequest) Reset()         { *m = UserSignupRequest{} }
func (m *UserSignupRequest) String() string { return proto.CompactTextString(m) }
func (*UserSignupRequest) ProtoMessage()    {}
func (*UserSignupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d51c8882b3c28c6, []int{1}
}

func (m *UserSignupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserSignupRequest.Unmarshal(m, b)
}
func (m *UserSignupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserSignupRequest.Marshal(b, m, deterministic)
}
func (m *UserSignupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserSignupRequest.Merge(m, src)
}
func (m *UserSignupRequest) XXX_Size() int {
	return xxx_messageInfo_UserSignupRequest.Size(m)
}
func (m *UserSignupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserSignupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserSignupRequest proto.InternalMessageInfo

func (m *UserSignupRequest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *UserSignupRequest) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *UserSignupRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *UserSignupRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *UserSignupRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type OrgSignupResponse struct {
	OrgId                *entityservice.Id `protobuf:"bytes,1,opt,name=orgId,proto3" json:"orgId,omitempty"`
	AdminId              *entityservice.Id `protobuf:"bytes,2,opt,name=adminId,proto3" json:"adminId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *OrgSignupResponse) Reset()         { *m = OrgSignupResponse{} }
func (m *OrgSignupResponse) String() string { return proto.CompactTextString(m) }
func (*OrgSignupResponse) ProtoMessage()    {}
func (*OrgSignupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d51c8882b3c28c6, []int{2}
}

func (m *OrgSignupResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrgSignupResponse.Unmarshal(m, b)
}
func (m *OrgSignupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrgSignupResponse.Marshal(b, m, deterministic)
}
func (m *OrgSignupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrgSignupResponse.Merge(m, src)
}
func (m *OrgSignupResponse) XXX_Size() int {
	return xxx_messageInfo_OrgSignupResponse.Size(m)
}
func (m *OrgSignupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OrgSignupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OrgSignupResponse proto.InternalMessageInfo

func (m *OrgSignupResponse) GetOrgId() *entityservice.Id {
	if m != nil {
		return m.OrgId
	}
	return nil
}

func (m *OrgSignupResponse) GetAdminId() *entityservice.Id {
	if m != nil {
		return m.AdminId
	}
	return nil
}

type UserSignupResponse struct {
	UserId               *entityservice.Id `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *UserSignupResponse) Reset()         { *m = UserSignupResponse{} }
func (m *UserSignupResponse) String() string { return proto.CompactTextString(m) }
func (*UserSignupResponse) ProtoMessage()    {}
func (*UserSignupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d51c8882b3c28c6, []int{3}
}

func (m *UserSignupResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserSignupResponse.Unmarshal(m, b)
}
func (m *UserSignupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserSignupResponse.Marshal(b, m, deterministic)
}
func (m *UserSignupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserSignupResponse.Merge(m, src)
}
func (m *UserSignupResponse) XXX_Size() int {
	return xxx_messageInfo_UserSignupResponse.Size(m)
}
func (m *UserSignupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserSignupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserSignupResponse proto.InternalMessageInfo

func (m *UserSignupResponse) GetUserId() *entityservice.Id {
	if m != nil {
		return m.UserId
	}
	return nil
}

func init() {
	proto.RegisterType((*OrgSignupRequest)(nil), "signup.OrgSignupRequest")
	proto.RegisterType((*UserSignupRequest)(nil), "signup.UserSignupRequest")
	proto.RegisterType((*OrgSignupResponse)(nil), "signup.OrgSignupResponse")
	proto.RegisterType((*UserSignupResponse)(nil), "signup.UserSignupResponse")
}

func init() { proto.RegisterFile("signup/signup.proto", fileDescriptor_2d51c8882b3c28c6) }

var fileDescriptor_2d51c8882b3c28c6 = []byte{
	// 358 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0xc1, 0x4e, 0xfa, 0x40,
	0x10, 0xc6, 0xff, 0xfd, 0x4b, 0x51, 0x86, 0x98, 0xc8, 0xea, 0xa1, 0x34, 0x1e, 0x48, 0x2f, 0x62,
	0x8c, 0xad, 0xa9, 0x0f, 0x60, 0x42, 0xbc, 0x70, 0xd1, 0xa4, 0xc4, 0x8b, 0xb7, 0x85, 0xae, 0xcb,
	0x1a, 0xba, 0x5b, 0x77, 0x5b, 0x0c, 0x67, 0x9f, 0xc1, 0x83, 0x6f, 0x6b, 0xd8, 0x29, 0x14, 0x14,
	0x39, 0xb5, 0xdf, 0x7c, 0x5f, 0x77, 0x7e, 0xb3, 0x53, 0x38, 0x35, 0x82, 0xcb, 0x32, 0x8f, 0xf0,
	0x11, 0xe6, 0x5a, 0x15, 0x8a, 0x34, 0x51, 0xf9, 0x3e, 0x93, 0x85, 0x28, 0x16, 0x86, 0xe9, 0xb9,
	0x98, 0xb0, 0x08, 0x15, 0x66, 0x82, 0x0f, 0x07, 0x4e, 0x1e, 0x35, 0x1f, 0xd9, 0x64, 0xc2, 0xde,
	0x4a, 0x66, 0x0a, 0x42, 0xa0, 0x21, 0x69, 0xc6, 0x3c, 0xa7, 0xe7, 0xf4, 0x5b, 0x89, 0x7d, 0x27,
	0x67, 0xe0, 0xe6, 0x53, 0x25, 0x99, 0xf7, 0xdf, 0x16, 0x51, 0x2c, 0xab, 0x2c, 0xa3, 0x62, 0xe6,
	0x1d, 0x60, 0xd5, 0x0a, 0x12, 0x81, 0x4b, 0xd3, 0x4c, 0x48, 0xaf, 0xd1, 0x73, 0xfa, 0xed, 0xb8,
	0x1b, 0x56, 0x58, 0x4f, 0x86, 0xe9, 0xad, 0x4e, 0x09, 0xe6, 0x82, 0x4f, 0x07, 0x3a, 0xbf, 0x4c,
	0x72, 0x0e, 0xad, 0x17, 0xa1, 0x4d, 0xf1, 0x50, 0xb3, 0xd4, 0x05, 0xe2, 0xc3, 0xd1, 0x8c, 0x56,
	0x26, 0x32, 0xad, 0xf5, 0xd2, 0x2b, 0x0d, 0xd3, 0xd6, 0x43, 0xb2, 0xb5, 0xae, 0x07, 0x69, 0xec,
	0x1c, 0xc4, 0xdd, 0x18, 0x24, 0x10, 0xd0, 0xd9, 0xb8, 0x1c, 0x93, 0x2b, 0x69, 0x18, 0xb9, 0x00,
	0x57, 0x69, 0x3e, 0x4c, 0x2d, 0x52, 0x3b, 0xee, 0x84, 0x5b, 0xd7, 0x1b, 0x0e, 0xd3, 0x04, 0x7d,
	0x72, 0x05, 0x87, 0x76, 0xbc, 0x61, 0x6a, 0x01, 0x77, 0x46, 0x57, 0x89, 0xe0, 0x0e, 0xc8, 0xe6,
	0x0d, 0x54, 0xbd, 0x2e, 0xa1, 0xb9, 0x04, 0xdf, 0xd7, 0xac, 0x0a, 0xc4, 0x5f, 0x0e, 0x1c, 0xe3,
	0xd7, 0x23, 0x34, 0xc9, 0x00, 0x5a, 0x6b, 0x7a, 0xe2, 0xad, 0x96, 0xf0, 0x73, 0xdb, 0x7e, 0x77,
	0x87, 0x83, 0xed, 0x83, 0x7f, 0xe4, 0x1e, 0xa0, 0xc6, 0x22, 0x7f, 0x6f, 0x72, 0xef, 0x29, 0x83,
	0xf8, 0xf9, 0x86, 0x8b, 0x62, 0x5a, 0x8e, 0xc3, 0x89, 0xca, 0xa2, 0xb9, 0x90, 0x2a, 0x9d, 0x6a,
	0xfa, 0x4a, 0xb9, 0xca, 0xe9, 0x2c, 0x7a, 0xa7, 0x0b, 0xc9, 0xe9, 0x35, 0xd7, 0xf9, 0x24, 0x52,
	0x9a, 0xe3, 0x39, 0xe3, 0xa6, 0xfd, 0x41, 0x6f, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0xcb, 0xf2,
	0x2e, 0x8b, 0xdb, 0x02, 0x00, 0x00,
}
